import { ProductInList } from "./products-lists.type";

export const productsConst: ProductInList[] = [
  {
    id: "1 defaultProductId",
    name: { ru: "Яблоко", en: "Apple" },
    svgKey: "apple",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "2 defaultProductId",
    name: { ru: "Морковь", en: "Carrot" },
    svgKey: "carrot",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "3 defaultProductId",
    name: { ru: "Абрикос", en: "Apricot" },
    svgKey: "apricot",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "4 defaultProductId",
    name: { ru: "Авокадо", en: "Avocado" },
    svgKey: "avocado",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "5 defaultProductId",
    name: { ru: "Ананас", en: "Pineapple" },
    svgKey: "pineapple",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "6 defaultProductId",
    name: { ru: "Апельсин", en: "Orange" },
    svgKey: "orange",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "7 defaultProductId",
    name: { ru: "Арбуз", en: "Watermelon" },
    svgKey: "watermelon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "8 defaultProductId",
    name: { ru: "Артишок", en: "Artichoke" },
    svgKey: "artichoke",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "9 defaultProductId",
    name: { ru: "Базилик", en: "Basil" },
    svgKey: "basil",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "10 defaultProductId",
    name: { ru: "Баклажан", en: "Eggplant" },
    svgKey: "eggplant",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "11 defaultProductId",
    name: { ru: "Банан", en: "Banana" },
    svgKey: "banana",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "12 defaultProductId",
    name: { ru: "Батат", en: "Sweet Potato" },
    svgKey: "sweet_potato",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "13 defaultProductId",
    name: { ru: "Перец сладкий", en: "Bell Pepper" },
    svgKey: "bell_pepper",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "14 defaultProductId",
    name: { ru: "Брокколи", en: "Broccoli" },
    svgKey: "broccoli",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "15 defaultProductId",
    name: { ru: "Виноград", en: "Grapes" },
    svgKey: "grapes",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "16 defaultProductId",
    name: { ru: "Горох", en: "Peas" },
    svgKey: "peas",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "17 defaultProductId",
    name: { ru: "Грейпфрут", en: "Grapefruit" },
    svgKey: "grapefruit",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "18 defaultProductId",
    name: { ru: "Дыня", en: "Melon" },
    svgKey: "melon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "19 defaultProductId",
    name: { ru: "Зеленый лук", en: "Green Onion" },
    svgKey: "green_onion",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "20 defaultProductId",
    name: { ru: "Зелень", en: "Greens" },
    svgKey: "greens",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "21 defaultProductId",
    name: { ru: "Имбирь", en: "Ginger" },
    svgKey: "ginger",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "22 defaultProductId",
    name: { ru: "Инжир", en: "Fig" },
    svgKey: "fig",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "23 defaultProductId",
    name: { ru: "Капуста", en: "Cabbage" },
    svgKey: "cabbage",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "24 defaultProductId",
    name: { ru: "Картофель", en: "Potato" },
    svgKey: "potato",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "25 defaultProductId",
    name: { ru: "Киви", en: "Kiwi" },
    svgKey: "kiwi",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "26 defaultProductId",
    name: { ru: "Клубника", en: "Strawberry" },
    svgKey: "strawberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    id: "27 defaultProductId",
    name: { ru: "Клюква", en: "Cranberry" },
    svgKey: "cranberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    id: "28 defaultProductId",
    name: { ru: "Кориандр", en: "Coriander" },
    svgKey: "coriander",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "29 defaultProductId",
    name: { ru: "Кукуруза", en: "Corn" },
    svgKey: "corn",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "30 defaultProductId",
    name: { ru: "Лайм", en: "Lime" },
    svgKey: "lime",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "31 defaultProductId",
    name: { ru: "Лимон", en: "Lemon" },
    svgKey: "lemon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "32 defaultProductId",
    name: { ru: "Лук", en: "Onion" },
    svgKey: "onion",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "33 defaultProductId",
    name: { ru: "Лук-порей", en: "Leek" },
    svgKey: "leek",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "34 defaultProductId",
    name: { ru: "Малина", en: "Raspberry" },
    svgKey: "raspberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    id: "35 defaultProductId",
    name: { ru: "Манго", en: "Mango" },
    svgKey: "mango",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "36 defaultProductId",
    name: { ru: "Мандарины", en: "Tangerines" },
    svgKey: "tangerines",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "37 defaultProductId",
    name: { ru: "Маракуйя", en: "Passion Fruit" },
    svgKey: "passion_fruit",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "38 defaultProductId",
    name: { ru: "Мята", en: "Mint" },
    svgKey: "mint",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "39 defaultProductId",
    name: { ru: "Нектарин", en: "Nectarine" },
    svgKey: "nectarine",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "40 defaultProductId",
    name: { ru: "Огурец", en: "Cucumber" },
    svgKey: "cucumber",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "41 defaultProductId",
    name: { ru: "Оливки", en: "Olives" },
    svgKey: "olives",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "42 defaultProductId",
    name: { ru: "Перец чили", en: "Chili Pepper" },
    svgKey: "chili_pepper",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "43 defaultProductId",
    name: { ru: "Персик", en: "Peach" },
    svgKey: "peach",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "44 defaultProductId",
    name: { ru: "Петрушка", en: "Parsley" },
    svgKey: "parsley",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "45 defaultProductId",
    name: { ru: "Томаты", en: "Tomatoes" },
    svgKey: "tomatoes",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "46 defaultProductId",
    name: { ru: "Томаты чери", en: "Cherry Tomatoes" },
    svgKey: "cherry_tomatoes",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "47 defaultProductId",
    name: { ru: "Редис", en: "Radish" },
    svgKey: "radish",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "48 defaultProductId",
    name: { ru: "Рукола", en: "Arugula" },
    svgKey: "arugula",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "49 defaultProductId",
    name: { ru: "Салат", en: "Lettuce" },
    svgKey: "lettuce",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "50 defaultProductId",
    name: { ru: "Свекла", en: "Beetroot" },
    svgKey: "beetroot",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "51 defaultProductId",
    name: { ru: "Сельдерей", en: "Celery" },
    svgKey: "celery",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "52 defaultProductId",
    name: { ru: "Сливы", en: "Plums" },
    svgKey: "plums",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "53 defaultProductId",
    name: { ru: "Спаржа", en: "Asparagus" },
    svgKey: "asparagus",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "54 defaultProductId",
    name: { ru: "Тыква", en: "Pumpkin" },
    svgKey: "pumpkin",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "55 defaultProductId",
    name: { ru: "Укроп", en: "Dill" },
    svgKey: "dill",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "56 defaultProductId",
    name: { ru: "Финики", en: "Dates" },
    svgKey: "dates",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    id: "57 defaultProductId",
    name: { ru: "Цветная капуста", en: "Cauliflower" },
    svgKey: "cauliflower",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "58 defaultProductId",
    name: { ru: "Цукини", en: "Zucchini" },
    svgKey: "zucchini",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "59 defaultProductId",
    name: { ru: "Черешня", en: "Cherry" },
    svgKey: "cherry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    id: "60 defaultProductId",
    name: { ru: "Черника", en: "Blueberry" },
    svgKey: "blueberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    id: "61 defaultProductId",
    name: { ru: "Чеснок", en: "Garlic" },
    svgKey: "garlic",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    id: "62 defaultProductId",
    name: { ru: "Шалфей", en: "Sage" },
    svgKey: "sage",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    id: "63 defaultProductId",
    name: { ru: "Корм для собак", en: "Dog Food" },
    svgKey: "dog_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    id: "64 defaultProductId",
    name: { ru: "Корм для кошек", en: "Cat Food" },
    svgKey: "cat_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    id: "65 defaultProductId",
    name: { ru: "Корм для рыб", en: "Fish Food" },
    svgKey: "fish_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    id: "66 defaultProductId",
    name: { ru: "Корм для птиц", en: "Bird Food" },
    svgKey: "bird_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    id: "67 defaultProductId",
    name: { ru: "Корм для грызунов", en: "Rodent Food" },
    svgKey: "rodent_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    id: "68 defaultProductId",
    name: { ru: "Салфетки бумажные", en: "Paper Napkins" },
    svgKey: "paper_napkins",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "69 defaultProductId",
    name: { ru: "Салфетки влажные", en: "Wet Wipes" },
    svgKey: "wet_wipes",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "70 defaultProductId",
    name: { ru: "Моющее средство для посуды", en: "Dish Soap" },
    svgKey: "dish_soap",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "71 defaultProductId",
    name: { ru: "Лампочки", en: "Light Bulbs" },
    svgKey: "light_bulbs",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "72 defaultProductId",
    name: { ru: "Пакеты для мусора", en: "Garbage Bags" },
    svgKey: "garbage_bags",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "73 defaultProductId",
    name: { ru: "Зубная паста", en: "Toothpaste" },
    svgKey: "toothpaste",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "74 defaultProductId",
    name: { ru: "Шампунь", en: "Shampoo" },
    svgKey: "shampoo",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "75 defaultProductId",
    name: { ru: "Мыло", en: "Soap" },
    svgKey: "soap",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "76 defaultProductId",
    name: { ru: "Туалетная бумага", en: "Toilet Paper" },
    svgKey: "toilet_paper",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "77 defaultProductId",
    name: { ru: "Стиральный порошок", en: "Laundry Detergent" },
    svgKey: "laundry_detergent",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "78 defaultProductId",
    name: { ru: "Губки для мытья посуды", en: "Dish Sponges" },
    svgKey: "dish_sponges",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "79 defaultProductId",
    name: { ru: "Освежитель воздуха", en: "Air Freshener" },
    svgKey: "air_freshener",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    id: "80 defaultProductId",
    name: { ru: "Говядина", en: "Beef" },
    svgKey: "beef",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "81 defaultProductId",
    name: { ru: "Свинина", en: "Pork" },
    svgKey: "pork",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "82 defaultProductId",
    name: { ru: "Курица", en: "Chicken" },
    svgKey: "chicken",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "83 defaultProductId",
    name: { ru: "Индейка", en: "Turkey" },
    svgKey: "turkey",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "84 defaultProductId",
    name: { ru: "Баранина", en: "Lamb" },
    svgKey: "lamb",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "85 defaultProductId",
    name: { ru: "Телятина", en: "Veal" },
    svgKey: "veal",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "86 defaultProductId",
    name: { ru: "Утка", en: "Duck" },
    svgKey: "duck",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "87 defaultProductId",
    name: { ru: "Кролик", en: "Rabbit" },
    svgKey: "rabbit",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "88 defaultProductId",
    name: { ru: "Фарш", en: "Ground Meat" },
    svgKey: "ground_meat",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "89 defaultProductId",
    name: { ru: "Сосиски", en: "Sausages" },
    svgKey: "sausages",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "90 defaultProductId",
    name: { ru: "Колбаса", en: "Salami" },
    svgKey: "salami",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "91 defaultProductId",
    name: { ru: "Ветчина", en: "Ham" },
    svgKey: "ham",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "92 defaultProductId",
    name: { ru: "Бекон", en: "Bacon" },
    svgKey: "bacon",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    id: "93 defaultProductId",
    name: { ru: "Лосось", en: "Salmon" },
    svgKey: "salmon",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "94 defaultProductId",
    name: { ru: "Треска", en: "Cod" },
    svgKey: "cod",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "95 defaultProductId",
    name: { ru: "Тунец", en: "Tuna" },
    svgKey: "tuna",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "96 defaultProductId",
    name: { ru: "Сельдь", en: "Herring" },
    svgKey: "herring",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "97 defaultProductId",
    name: { ru: "Форель", en: "Trout" },
    svgKey: "trout",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "98 defaultProductId",
    name: { ru: "Скумбрия", en: "Mackerel" },
    svgKey: "mackerel",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "99 defaultProductId",
    name: { ru: "Камбала", en: "Flounder" },
    svgKey: "flounder",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "100 defaultProductId",
    name: { ru: "Карп", en: "Carp" },
    svgKey: "carp",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "101 defaultProductId",
    name: { ru: "Окунь", en: "Perch" },
    svgKey: "perch",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "102 defaultProductId",
    name: { ru: "Щука", en: "Pike" },
    svgKey: "pike",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "103 defaultProductId",
    name: { ru: "Креветки", en: "Shrimp" },
    svgKey: "shrimp",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "104 defaultProductId",
    name: { ru: "Кальмары", en: "Squid" },
    svgKey: "squid",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "105 defaultProductId",
    name: { ru: "Мидии", en: "Mussels" },
    svgKey: "mussels",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "106 defaultProductId",
    name: { ru: "Устрицы", en: "Oysters" },
    svgKey: "oysters",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    id: "107 defaultProductId",
    name: { ru: "Кетчуп", en: "Ketchup" },
    svgKey: "ketchup",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "108 defaultProductId",
    name: { ru: "Майонез", en: "Mayonnaise" },
    svgKey: "mayonnaise",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "109 defaultProductId",
    name: { ru: "Горчица", en: "Mustard" },
    svgKey: "mustard",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "110 defaultProductId",
    name: { ru: "Соевый соус", en: "Soy Sauce" },
    svgKey: "soy_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "111 defaultProductId",
    name: { ru: "Барбекю соус", en: "BBQ Sauce" },
    svgKey: "bbq_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "112 defaultProductId",
    name: { ru: "Тартар", en: "Tartar Sauce" },
    svgKey: "tartar_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "113 defaultProductId",
    name: { ru: "Сальса", en: "Salsa" },
    svgKey: "salsa",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "114 defaultProductId",
    name: { ru: "Песто", en: "Pesto" },
    svgKey: "pesto",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "115 defaultProductId",
    name: { ru: "Сырный соус", en: "Cheese Sauce" },
    svgKey: "cheese_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "116 defaultProductId",
    name: { ru: "Чесночный соус", en: "Garlic Sauce" },
    svgKey: "garlic_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "117 defaultProductId",
    name: { ru: "Острый соус", en: "Hot Sauce" },
    svgKey: "hot_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "118 defaultProductId",
    name: { ru: "Ранч", en: "Ranch Dressing" },
    svgKey: "ranch_dressing",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "119 defaultProductId",
    name: { ru: "Терияки", en: "Teriyaki Sauce" },
    svgKey: "teriyaki_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    id: "120 defaultProductId",
    name: { ru: "Сыр", en: "Cheese" },
    svgKey: "cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "121 defaultProductId",
    name: { ru: "Сыр твердый", en: "Hard Cheese" },
    svgKey: "hard_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "122 defaultProductId",
    name: { ru: "Сыр мягкий", en: "Soft Cheese" },
    svgKey: "soft_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "123 defaultProductId",
    name: { ru: "Сыр полутвердый", en: "Semi-Hard Cheese" },
    svgKey: "semi_hard_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "124 defaultProductId",
    name: { ru: "Моцарелла", en: "Mozzarella" },
    svgKey: "mozzarella",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "125 defaultProductId",
    name: { ru: "Чеддер", en: "Cheddar" },
    svgKey: "cheddar",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "126 defaultProductId",
    name: { ru: "Пармезан", en: "Parmesan" },
    svgKey: "parmesan",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "127 defaultProductId",
    name: { ru: "Фета", en: "Feta" },
    svgKey: "feta",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "128 defaultProductId",
    name: { ru: "Бри", en: "Brie" },
    svgKey: "brie",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "129 defaultProductId",
    name: { ru: "Тофу", en: "Tofu" },
    svgKey: "tofu",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "130 defaultProductId",
    name: { ru: "Гауда", en: "Gouda" },
    svgKey: "gouda",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "131 defaultProductId",
    name: { ru: "Камамбер", en: "Camembert" },
    svgKey: "camembert",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "132 defaultProductId",
    name: { ru: "Рикотта", en: "Ricotta" },
    svgKey: "ricotta",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "133 defaultProductId",
    name: { ru: "Горгонзола", en: "Gorgonzola" },
    svgKey: "gorgonzola",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "134 defaultProductId",
    name: { ru: "Рокфор", en: "Roquefort" },
    svgKey: "roquefort",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "135 defaultProductId",
    name: { ru: "Маскарпоне", en: "Mascarpone" },
    svgKey: "mascarpone",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "136 defaultProductId",
    name: { ru: "Эмменталь", en: "Emmental" },
    svgKey: "emmental",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    id: "137 defaultProductId",
    name: { ru: "Молоко", en: "Milk" },
    svgKey: "milk",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "138 defaultProductId",
    name: { ru: "Йогурт", en: "Yogurt" },
    svgKey: "yogurt",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "139 defaultProductId",
    name: { ru: "Сметана", en: "Sour Cream" },
    svgKey: "sour_cream",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "140 defaultProductId",
    name: { ru: "Творог", en: "Cottage Cheese" },
    svgKey: "cottage_cheese",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "141 defaultProductId",
    name: { ru: "Кефир", en: "Kefir" },
    svgKey: "kefir",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "142 defaultProductId",
    name: { ru: "Сливки", en: "Cream" },
    svgKey: "cream",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "143 defaultProductId",
    name: { ru: "Масло сливочное", en: "Butter" },
    svgKey: "butter",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    id: "144 defaultProductId",
    name: { ru: "Яйца", en: "Eggs" },
    svgKey: "eggs",
    quantity: "",
    category: { ru: "Яйца", en: "Eggs" },
    isPushed: false,
  },
  {
    id: "145 defaultProductId",
    name: { ru: "Хлеб", en: "Bread" },
    svgKey: "bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "146 defaultProductId",
    name: { ru: "Хлеб черный", en: "Dark Bread" },
    svgKey: "dark_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "147 defaultProductId",
    name: { ru: "Хлеб белый", en: "White Bread" },
    svgKey: "white_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "148 defaultProductId",
    name: { ru: "Хлеб серый", en: "Gray Bread" },
    svgKey: "gray_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "149 defaultProductId",
    name: { ru: "Багет", en: "French Baguette" },
    svgKey: "french_baguette",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "150 defaultProductId",
    name: { ru: "Чиабатта", en: "Ciabatta" },
    svgKey: "ciabatta",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "151 defaultProductId",
    name: { ru: "Ржаной хлеб", en: "Rye Bread" },
    svgKey: "rye_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "152 defaultProductId",
    name: { ru: "Цельнозерновой хлеб", en: "Whole Grain Bread" },
    svgKey: "whole_grain_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "153 defaultProductId",
    name: { ru: "Хлеб с семечками", en: "Seeded Bread" },
    svgKey: "seeded_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "154 defaultProductId",
    name: { ru: "Булочки", en: "Buns" },
    svgKey: "buns",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "155 defaultProductId",
    name: { ru: "Круассаны", en: "Croissants" },
    svgKey: "croissants",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "156 defaultProductId",
    name: { ru: "Лаваш", en: "Lavash" },
    svgKey: "lavash",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "157 defaultProductId",
    name: { ru: "Пита", en: "Pita" },
    svgKey: "pita",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "158 defaultProductId",
    name: { ru: "Фокачча", en: "Focaccia" },
    svgKey: "focaccia",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "159 defaultProductId",
    name: { ru: "Хлебцы", en: "Crispbread" },
    svgKey: "crispbread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "160 defaultProductId",
    name: { ru: "Хлеб с отрубями", en: "Bran Bread" },
    svgKey: "bran_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "161 defaultProductId",
    name: { ru: "Тостовый хлеб", en: "Toast Bread" },
    svgKey: "toast_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    id: "162 defaultProductId",
    name: { ru: "Черный перец", en: "Black Pepper" },
    svgKey: "black_pepper",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "163 defaultProductId",
    name: { ru: "Красный перец", en: "Red Pepper" },
    svgKey: "red_pepper",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "164 defaultProductId",
    name: { ru: "Куркума", en: "Turmeric" },
    svgKey: "turmeric",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "165 defaultProductId",
    name: { ru: "Корица", en: "Cinnamon" },
    svgKey: "cinnamon",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "166 defaultProductId",
    name: { ru: "Кардамон", en: "Cardamom" },
    svgKey: "cardamom",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "167 defaultProductId",
    name: { ru: "Гвоздика", en: "Cloves" },
    svgKey: "cloves",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "168 defaultProductId",
    name: { ru: "Мускатный орех", en: "Nutmeg" },
    svgKey: "nutmeg",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "169 defaultProductId",
    name: { ru: "Паприка", en: "Paprika" },
    svgKey: "paprika",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "170 defaultProductId",
    name: { ru: "Орегано", en: "Oregano" },
    svgKey: "oregano",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "171 defaultProductId",
    name: { ru: "Базилик сушеный", en: "Dried Basil" },
    svgKey: "dried_basil",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "172 defaultProductId",
    name: { ru: "Тимьян сушеный", en: "Dried Thyme" },
    svgKey: "dried_thyme",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "173 defaultProductId",
    name: { ru: "Розмарин сушеный", en: "Dried Rosemary" },
    svgKey: "dried_rosemary",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "174 defaultProductId",
    name: { ru: "Карри", en: "Curry" },
    svgKey: "curry",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "175 defaultProductId",
    name: { ru: "Шафран", en: "Saffron" },
    svgKey: "saffron",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "176 defaultProductId",
    name: { ru: "Имбирь молотый", en: "Ground Ginger" },
    svgKey: "ground_ginger",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "177 defaultProductId",
    name: { ru: "Чеснок молотый", en: "Ground Garlic" },
    svgKey: "ground_garlic",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "178 defaultProductId",
    name: { ru: "Кориандр молотый", en: "Ground Coriander" },
    svgKey: "ground_coriander",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "179 defaultProductId",
    name: { ru: "Тмин", en: "Cumin" },
    svgKey: "cumin",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "180 defaultProductId",
    name: { ru: "Семена горчицы", en: "Mustard Seeds" },
    svgKey: "mustard_seeds",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    id: "181 defaultProductId",
    name: { ru: "Вино", en: "Wine" },
    svgKey: "wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "182 defaultProductId",
    name: { ru: "Вино красное", en: "Red Wine" },
    svgKey: "red_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "183 defaultProductId",
    name: { ru: "Вино белое", en: "White Wine" },
    svgKey: "white_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "184 defaultProductId",
    name: { ru: "Вино розовое", en: "Rose Wine" },
    svgKey: "rose_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "185 defaultProductId",
    name: { ru: "Пиво", en: "Beer" },
    svgKey: "beer",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "186 defaultProductId",
    name: { ru: "Шампанское", en: "Champagne" },
    svgKey: "champagne",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "187 defaultProductId",
    name: { ru: "Виски", en: "Whiskey" },
    svgKey: "whiskey",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "188 defaultProductId",
    name: { ru: "Водка", en: "Vodka" },
    svgKey: "vodka",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "189 defaultProductId",
    name: { ru: "Джин", en: "Gin" },
    svgKey: "gin",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "190 defaultProductId",
    name: { ru: "Ром", en: "Rum" },
    svgKey: "rum",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "191 defaultProductId",
    name: { ru: "Текила", en: "Tequila" },
    svgKey: "tequila",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "192 defaultProductId",
    name: { ru: "Коньяк", en: "Cognac" },
    svgKey: "cognac",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "193 defaultProductId",
    name: { ru: "Бренди", en: "Brandy" },
    svgKey: "brandy",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "194 defaultProductId",
    name: { ru: "Вермут", en: "Vermouth" },
    svgKey: "vermouth",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "195 defaultProductId",
    name: { ru: "Саке", en: "Sake" },
    svgKey: "sake",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    id: "196 defaultProductId",
    name: { ru: "Абсент", en: "Absinthe" },
    svgKey: "absinthe",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
];
