import { ProductInList } from "./products-lists.type";

export const productsConst: ProductInList[] = [
  {
    name: { ru: "Яблоко", en: "Apple" },
    svgKey: "apple",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Морковь", en: "Carrot" },
    svgKey: "carrot",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Абрикос", en: "Apricot" },
    svgKey: "apricot",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Авокадо", en: "Avocado" },
    svgKey: "avocado",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Ананас", en: "Pineapple" },
    svgKey: "pineapple",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Апельсин", en: "Orange" },
    svgKey: "orange",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Арбуз", en: "Watermelon" },
    svgKey: "watermelon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Артишок", en: "Artichoke" },
    svgKey: "artichoke",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Базилик", en: "Basil" },
    svgKey: "basil",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Баклажан", en: "Eggplant" },
    svgKey: "eggplant",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Банан", en: "Banana" },
    svgKey: "banana",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Батат", en: "Sweet Potato" },
    svgKey: "sweet_potato",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Перец сладкий", en: "Bell Pepper" },
    svgKey: "bell_pepper",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Брокколи", en: "Broccoli" },
    svgKey: "broccoli",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Виноград", en: "Grapes" },
    svgKey: "grapes",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Горох", en: "Peas" },
    svgKey: "peas",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Грейпфрут", en: "Grapefruit" },
    svgKey: "grapefruit",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Дыня", en: "Melon" },
    svgKey: "melon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Зеленый лук", en: "Green Onion" },
    svgKey: "green_onion",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Зелень", en: "Greens" },
    svgKey: "greens",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Имбирь", en: "Ginger" },
    svgKey: "ginger",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Инжир", en: "Fig" },
    svgKey: "fig",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Капуста", en: "Cabbage" },
    svgKey: "cabbage",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Картофель", en: "Potato" },
    svgKey: "potato",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Киви", en: "Kiwi" },
    svgKey: "kiwi",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Клубника", en: "Strawberry" },
    svgKey: "strawberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    name: { ru: "Клюква", en: "Cranberry" },
    svgKey: "cranberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    name: { ru: "Кориандр", en: "Coriander" },
    svgKey: "coriander",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Кукуруза", en: "Corn" },
    svgKey: "corn",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Лайм", en: "Lime" },
    svgKey: "lime",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Лимон", en: "Lemon" },
    svgKey: "lemon",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Лук", en: "Onion" },
    svgKey: "onion",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Лук-порей", en: "Leek" },
    svgKey: "leek",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Малина", en: "Raspberry" },
    svgKey: "raspberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    name: { ru: "Манго", en: "Mango" },
    svgKey: "mango",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Мандарины", en: "Tangerines" },
    svgKey: "tangerines",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Маракуйя", en: "Passion Fruit" },
    svgKey: "passion_fruit",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Мята", en: "Mint" },
    svgKey: "mint",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Нектарин", en: "Nectarine" },
    svgKey: "nectarine",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Огурец", en: "Cucumber" },
    svgKey: "cucumber",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Оливки", en: "Olives" },
    svgKey: "olives",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Перец чили", en: "Chili Pepper" },
    svgKey: "chili_pepper",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Персик", en: "Peach" },
    svgKey: "peach",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Петрушка", en: "Parsley" },
    svgKey: "parsley",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Томаты", en: "Tomatoes" },
    svgKey: "tomatoes",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Томаты чери", en: "Cherry Tomatoes" },
    svgKey: "cherry_tomatoes",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Редис", en: "Radish" },
    svgKey: "radish",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Рукола", en: "Arugula" },
    svgKey: "arugula",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Салат", en: "Lettuce" },
    svgKey: "lettuce",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Свекла", en: "Beetroot" },
    svgKey: "beetroot",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Сельдерей", en: "Celery" },
    svgKey: "celery",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Сливы", en: "Plums" },
    svgKey: "plums",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Спаржа", en: "Asparagus" },
    svgKey: "asparagus",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Тыква", en: "Pumpkin" },
    svgKey: "pumpkin",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Укроп", en: "Dill" },
    svgKey: "dill",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Финики", en: "Dates" },
    svgKey: "dates",
    quantity: "",
    category: { ru: "Фрукты", en: "Fruits" },
    isPushed: false,
  },
  {
    name: { ru: "Цветная капуста", en: "Cauliflower" },
    svgKey: "cauliflower",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Цукини", en: "Zucchini" },
    svgKey: "zucchini",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Черешня", en: "Cherry" },
    svgKey: "cherry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    name: { ru: "Черника", en: "Blueberry" },
    svgKey: "blueberry",
    quantity: "",
    category: { ru: "Ягоды", en: "Berries" },
    isPushed: false,
  },
  {
    name: { ru: "Чеснок", en: "Garlic" },
    svgKey: "garlic",
    quantity: "",
    category: { ru: "Овощи", en: "Vegetables" },
    isPushed: false,
  },
  {
    name: { ru: "Шалфей", en: "Sage" },
    svgKey: "sage",
    quantity: "",
    category: { ru: "Зелень", en: "Herbs" },
    isPushed: false,
  },
  {
    name: { ru: "Корм для собак", en: "Dog Food" },
    svgKey: "dog_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    name: { ru: "Корм для кошек", en: "Cat Food" },
    svgKey: "cat_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    name: { ru: "Корм для рыб", en: "Fish Food" },
    svgKey: "fish_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    name: { ru: "Корм для птиц", en: "Bird Food" },
    svgKey: "bird_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    name: { ru: "Корм для грызунов", en: "Rodent Food" },
    svgKey: "rodent_food",
    quantity: "",
    category: { ru: "Зоотовары", en: "Pet Supplies" },
    isPushed: false,
  },
  {
    name: { ru: "Салфетки бумажные", en: "Paper Napkins" },
    svgKey: "paper_napkins",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Салфетки влажные", en: "Wet Wipes" },
    svgKey: "wet_wipes",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Моющее средство для посуды", en: "Dish Soap" },
    svgKey: "dish_soap",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Лампочки", en: "Light Bulbs" },
    svgKey: "light_bulbs",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Пакеты для мусора", en: "Garbage Bags" },
    svgKey: "garbage_bags",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Зубная паста", en: "Toothpaste" },
    svgKey: "toothpaste",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Шампунь", en: "Shampoo" },
    svgKey: "shampoo",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Мыло", en: "Soap" },
    svgKey: "soap",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Туалетная бумага", en: "Toilet Paper" },
    svgKey: "toilet_paper",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Стиральный порошок", en: "Laundry Detergent" },
    svgKey: "laundry_detergent",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Губки для мытья посуды", en: "Dish Sponges" },
    svgKey: "dish_sponges",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Освежитель воздуха", en: "Air Freshener" },
    svgKey: "air_freshener",
    quantity: "",
    category: { ru: "Товары для дома", en: "Household Items" },
    isPushed: false,
  },
  {
    name: { ru: "Говядина", en: "Beef" },
    svgKey: "beef",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Свинина", en: "Pork" },
    svgKey: "pork",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Курица", en: "Chicken" },
    svgKey: "chicken",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Индейка", en: "Turkey" },
    svgKey: "turkey",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Баранина", en: "Lamb" },
    svgKey: "lamb",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Телятина", en: "Veal" },
    svgKey: "veal",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Утка", en: "Duck" },
    svgKey: "duck",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Кролик", en: "Rabbit" },
    svgKey: "rabbit",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Фарш", en: "Ground Meat" },
    svgKey: "ground_meat",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Сосиски", en: "Sausages" },
    svgKey: "sausages",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Колбаса", en: "Salami" },
    svgKey: "salami",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Ветчина", en: "Ham" },
    svgKey: "ham",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Бекон", en: "Bacon" },
    svgKey: "bacon",
    quantity: "",
    category: { ru: "Мясо", en: "Meat" },
    isPushed: false,
  },
  {
    name: { ru: "Лосось", en: "Salmon" },
    svgKey: "salmon",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Треска", en: "Cod" },
    svgKey: "cod",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Тунец", en: "Tuna" },
    svgKey: "tuna",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Сельдь", en: "Herring" },
    svgKey: "herring",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Форель", en: "Trout" },
    svgKey: "trout",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Скумбрия", en: "Mackerel" },
    svgKey: "mackerel",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Камбала", en: "Flounder" },
    svgKey: "flounder",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Карп", en: "Carp" },
    svgKey: "carp",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Окунь", en: "Perch" },
    svgKey: "perch",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Щука", en: "Pike" },
    svgKey: "pike",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Креветки", en: "Shrimp" },
    svgKey: "shrimp",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Кальмары", en: "Squid" },
    svgKey: "squid",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Мидии", en: "Mussels" },
    svgKey: "mussels",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Устрицы", en: "Oysters" },
    svgKey: "oysters",
    quantity: "",
    category: { ru: "Рыба и морепродукты", en: "Fish and Seafood" },
    isPushed: false,
  },
  {
    name: { ru: "Кетчуп", en: "Ketchup" },
    svgKey: "ketchup",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Майонез", en: "Mayonnaise" },
    svgKey: "mayonnaise",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Горчица", en: "Mustard" },
    svgKey: "mustard",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Соевый соус", en: "Soy Sauce" },
    svgKey: "soy_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Барбекю соус", en: "BBQ Sauce" },
    svgKey: "bbq_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Тартар", en: "Tartar Sauce" },
    svgKey: "tartar_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Сальса", en: "Salsa" },
    svgKey: "salsa",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Песто", en: "Pesto" },
    svgKey: "pesto",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Сырный соус", en: "Cheese Sauce" },
    svgKey: "cheese_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Чесночный соус", en: "Garlic Sauce" },
    svgKey: "garlic_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Острый соус", en: "Hot Sauce" },
    svgKey: "hot_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Ранч", en: "Ranch Dressing" },
    svgKey: "ranch_dressing",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Терияки", en: "Teriyaki Sauce" },
    svgKey: "teriyaki_sauce",
    quantity: "",
    category: { ru: "Соусы", en: "Sauces" },
    isPushed: false,
  },
  {
    name: { ru: "Сыр", en: "Cheese" },
    svgKey: "cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Сыр твердый", en: "Hard Cheese" },
    svgKey: "hard_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Сыр мягкий", en: "Soft Cheese" },
    svgKey: "soft_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Сыр полутвердый", en: "Semi-Hard Cheese" },
    svgKey: "semi_hard_cheese",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Моцарелла", en: "Mozzarella" },
    svgKey: "mozzarella",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Чеддер", en: "Cheddar" },
    svgKey: "cheddar",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Пармезан", en: "Parmesan" },
    svgKey: "parmesan",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Фета", en: "Feta" },
    svgKey: "feta",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Бри", en: "Brie" },
    svgKey: "brie",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Тофу", en: "Tofu" },
    svgKey: "tofu",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Гауда", en: "Gouda" },
    svgKey: "gouda",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Камамбер", en: "Camembert" },
    svgKey: "camembert",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Рикотта", en: "Ricotta" },
    svgKey: "ricotta",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Горгонзола", en: "Gorgonzola" },
    svgKey: "gorgonzola",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Рокфор", en: "Roquefort" },
    svgKey: "roquefort",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Маскарпоне", en: "Mascarpone" },
    svgKey: "mascarpone",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Эмменталь", en: "Emmental" },
    svgKey: "emmental",
    quantity: "",
    category: { ru: "Сыр", en: "Cheese" },
    isPushed: false,
  },
  {
    name: { ru: "Молоко", en: "Milk" },
    svgKey: "milk",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Йогурт", en: "Yogurt" },
    svgKey: "yogurt",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Сметана", en: "Sour Cream" },
    svgKey: "sour_cream",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Творог", en: "Cottage Cheese" },
    svgKey: "cottage_cheese",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Кефир", en: "Kefir" },
    svgKey: "kefir",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Сливки", en: "Cream" },
    svgKey: "cream",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Масло сливочное", en: "Butter" },
    svgKey: "butter",
    quantity: "",
    category: { ru: "Молочные продукты", en: "Dairy" },
    isPushed: false,
  },
  {
    name: { ru: "Яйца", en: "Eggs" },
    svgKey: "eggs",
    quantity: "",
    category: { ru: "Яйца", en: "Eggs" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб", en: "Bread" },
    svgKey: "bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб черный", en: "Dark Bread" },
    svgKey: "dark_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб белый", en: "White Bread" },
    svgKey: "white_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб серый", en: "Gray Bread" },
    svgKey: "gray_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Багет", en: "French Baguette" },
    svgKey: "french_baguette",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Чиабатта", en: "Ciabatta" },
    svgKey: "ciabatta",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Ржаной хлеб", en: "Rye Bread" },
    svgKey: "rye_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Цельнозерновой хлеб", en: "Whole Grain Bread" },
    svgKey: "whole_grain_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб с семечками", en: "Seeded Bread" },
    svgKey: "seeded_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Булочки", en: "Buns" },
    svgKey: "buns",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Круассаны", en: "Croissants" },
    svgKey: "croissants",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Лаваш", en: "Lavash" },
    svgKey: "lavash",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Пита", en: "Pita" },
    svgKey: "pita",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Фокачча", en: "Focaccia" },
    svgKey: "focaccia",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлебцы", en: "Crispbread" },
    svgKey: "crispbread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Хлеб с отрубями", en: "Bran Bread" },
    svgKey: "bran_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Тостовый хлеб", en: "Toast Bread" },
    svgKey: "toast_bread",
    quantity: "",
    category: { ru: "Хлеб", en: "Bread" },
    isPushed: false,
  },
  {
    name: { ru: "Черный перец", en: "Black Pepper" },
    svgKey: "black_pepper",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Красный перец", en: "Red Pepper" },
    svgKey: "red_pepper",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Куркума", en: "Turmeric" },
    svgKey: "turmeric",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Корица", en: "Cinnamon" },
    svgKey: "cinnamon",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Кардамон", en: "Cardamom" },
    svgKey: "cardamom",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Гвоздика", en: "Cloves" },
    svgKey: "cloves",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Мускатный орех", en: "Nutmeg" },
    svgKey: "nutmeg",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Паприка", en: "Paprika" },
    svgKey: "paprika",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Орегано", en: "Oregano" },
    svgKey: "oregano",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Базилик сушеный", en: "Dried Basil" },
    svgKey: "dried_basil",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Тимьян сушеный", en: "Dried Thyme" },
    svgKey: "dried_thyme",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Розмарин сушеный", en: "Dried Rosemary" },
    svgKey: "dried_rosemary",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Карри", en: "Curry" },
    svgKey: "curry",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Шафран", en: "Saffron" },
    svgKey: "saffron",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Имбирь молотый", en: "Ground Ginger" },
    svgKey: "ground_ginger",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Чеснок молотый", en: "Ground Garlic" },
    svgKey: "ground_garlic",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Кориандр молотый", en: "Ground Coriander" },
    svgKey: "ground_coriander",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Тмин", en: "Cumin" },
    svgKey: "cumin",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Семена горчицы", en: "Mustard Seeds" },
    svgKey: "mustard_seeds",
    quantity: "",
    category: { ru: "Специи", en: "Spices" },
    isPushed: false,
  },
  {
    name: { ru: "Вино", en: "Wine" },
    svgKey: "wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Вино красное", en: "Red Wine" },
    svgKey: "red_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Вино белое", en: "White Wine" },
    svgKey: "white_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Вино розовое", en: "Rose Wine" },
    svgKey: "rose_wine",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Пиво", en: "Beer" },
    svgKey: "beer",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Шампанское", en: "Champagne" },
    svgKey: "champagne",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Виски", en: "Whiskey" },
    svgKey: "whiskey",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Водка", en: "Vodka" },
    svgKey: "vodka",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Джин", en: "Gin" },
    svgKey: "gin",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Ром", en: "Rum" },
    svgKey: "rum",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Текила", en: "Tequila" },
    svgKey: "tequila",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Коньяк", en: "Cognac" },
    svgKey: "cognac",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Бренди", en: "Brandy" },
    svgKey: "brandy",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Вермут", en: "Vermouth" },
    svgKey: "vermouth",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Саке", en: "Sake" },
    svgKey: "sake",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
  {
    name: { ru: "Абсент", en: "Absinthe" },
    svgKey: "absinthe",
    quantity: "",
    category: { ru: "Алкоголь", en: "Alcohol" },
    isPushed: false,
  },
];
