import {
  AppleSvgComponent,
  ApricotSvgComponent,
  AvocadoSvgComponent,
  CarrotSvgComponent,
  OrangeSvg,
  PineappleSvg,
  WatermelonSvg,
  ArtichokeSvg,
  BasilSvg,
  EggplantSvg,
  BananaSvg,
  SweetPotatoSvg,
  BellPepperSvg,
  BroccoliSvg,
  GrapesSvg,
  PeasSvg,
  GrapefruitSvg,
  MelonSvg,
  GreenOnionSVG,
  Greens,
  Ginger,
  Fig,
  Cabbage,
  Potato,
  Kiwi,
  Strawberry,
  Cranberry,
  Coriander,
  Corn,
  Lime,
  Lemon,
  Onion,
  Leek,
  Raspberry,
  Mango,
  Tangerines,
  PassionFruit,
  Mint,
  Nectarine,
  Cucumber,
  Olives,
  ChiliPepper,
  Peach,
  Parsley,
  Tomatoes,
  CherryTomatoes,
  Radish,
  Arugula,
  Lettuce,
  Beetroot,
  Celery,
  Plums,
  Asparagus,
  Pumpkin,
  Dill,
  Dates,
  Cauliflower,
  Zucchini,
  Cherry,
  Blueberry,
  Garlic,
  Sage,
  DogFood,
  CatFood,
  FishFood,
  BirdFood,
  RodentFood,
  PaperNapkins,
  WetWipes,
  DishSoap,
  LightBulbs,
  GarbageBags,
  Toothpaste,
  ToiletPaper,
  LaundryDetergent,
  DishSponges,
  AirFreshener,
  Soap,
  Shampoo,
  Beef,
  Chicken,
  Lamb,
  Turkey,
  Veal,
  Duck,
  Rabbit,
  GroundMeat,
  Sausages,
  Salami,
  Ham,
  Bacon,
  Pork,
  Flounder,
  Fish,
  Shrimp,
  Mussels,
  Squid,
  Oysters,
  Sauces,
  Cheese,
  Feta,
  Tofu,
  Mozzarella,
  Eggs,
  Butter,
  Cream,
  Milk,
  CottageCheese,
  SourCream,
  Yogurt,
  Bread,
  Pita,
  ToastBread,
  CrispBread,
  Focaccia,
  Croissant,
  Ciabatta,
  FrenchBaguette,
  Buns,
  Spices,
  Wine,
  Alcohol,
  Sake,
  Vermouth,
  Champagne,
  Beer,
} from "@/assets";
type SvgScheme = { [key: string]: JSX.Element };
const commonProps = { fill: "white", width: 35, height: 35 };
export const svgScheme: SvgScheme = {
  wine: <Wine {...commonProps} />,
  red_wine: <Wine {...commonProps} />,
  white_wine: <Wine {...commonProps} />,
  rose_wine: <Wine {...commonProps} />,
  absinthe: <Vermouth {...commonProps} />,
  sake: <Sake {...commonProps} />,
  vermouth: <Vermouth {...commonProps} />,
  vodka: <Alcohol {...commonProps} />,
  gin: <Alcohol {...commonProps} />,
  rum: <Alcohol {...commonProps} />,
  tequila: <Alcohol {...commonProps} />,
  cognac: <Alcohol {...commonProps} />,
  brandy: <Alcohol {...commonProps} />,
  whiskey: <Alcohol {...commonProps} />,
  champagne: <Champagne {...commonProps} />,
  beer: <Beer {...commonProps} />,
  red_pepper: <Spices {...commonProps} />,
  turmeric: <Spices {...commonProps} />,
  cinnamon: <Spices {...commonProps} />,
  cardamom: <Spices {...commonProps} />,
  cloves: <Spices {...commonProps} />,
  nutmeg: <Spices {...commonProps} />,
  paprika: <Spices {...commonProps} />,
  oregano: <Spices {...commonProps} />,
  dried_basil: <Spices {...commonProps} />,
  dried_thyme: <Spices {...commonProps} />,
  dried_rosemary: <Spices {...commonProps} />,
  curry: <Spices {...commonProps} />,
  saffron: <Spices {...commonProps} />,
  ground_ginger: <Spices {...commonProps} />,
  ground_garlic: <Spices {...commonProps} />,
  ground_coriander: <Spices {...commonProps} />,
  cumin: <Spices {...commonProps} />,
  mustard_seeds: <Spices {...commonProps} />,
  black_pepper: <Spices {...commonProps} />,
  toast_bread: <ToastBread {...commonProps} />,
  bran_bread: <Bread {...commonProps} />,
  crispbread: <CrispBread {...commonProps} />,
  focaccia: <Focaccia {...commonProps} />,
  pita: <Pita {...commonProps} />,
  lavash: <Pita {...commonProps} />,
  croissants: <Croissant {...commonProps} />,
  ciabatta: <Ciabatta {...commonProps} />,
  rye_bread: <Bread {...commonProps} />,
  whole_grain_bread: <Bread {...commonProps} />,
  seeded_bread: <Bread {...commonProps} />,
  buns: <Buns {...commonProps} />,
  french_baguette: <FrenchBaguette {...commonProps} />,
  dark_bread: <Bread {...commonProps} />,
  white_bread: <Bread {...commonProps} />,
  gray_bread: <Bread {...commonProps} />,
  bread: <Bread {...commonProps} />,
  eggs: <Eggs {...commonProps} />,
  butter: <Butter {...commonProps} />,
  cream: <Cream {...commonProps} />,
  kefir: <Milk {...commonProps} />,
  cottage_cheese: <CottageCheese {...commonProps} />,
  sour_cream: <SourCream {...commonProps} />,
  yogurt: <Yogurt {...commonProps} />,
  milk: <Milk {...commonProps} />,
  cheese: <Cheese {...commonProps} />,
  hard_cheese: <Cheese {...commonProps} />,
  gouda: <Cheese {...commonProps} />,
  camembert: <Cheese {...commonProps} />,
  ricotta: <Cheese {...commonProps} />,
  gorgonzola: <Cheese {...commonProps} />,
  roquefort: <Cheese {...commonProps} />,
  mascarpone: <Cheese {...commonProps} />,
  emmental: <Cheese {...commonProps} />,
  soft_cheese: <Cheese {...commonProps} />,
  semi_hard_cheese: <Cheese {...commonProps} />,
  cheddar: <Cheese {...commonProps} />,
  parmesan: <Cheese {...commonProps} />,
  feta: <Feta {...commonProps} />,
  brie: <Cheese {...commonProps} />,
  tofu: <Tofu {...commonProps} />,
  mozzarella: <Mozzarella {...commonProps} />,
  salsa: <Sauces {...commonProps} />,
  pesto: <Sauces {...commonProps} />,
  cheese_sauce: <Sauces {...commonProps} />,
  garlic_sauce: <Sauces {...commonProps} />,
  hot_sauce: <Sauces {...commonProps} />,
  ranch_dressing: <Sauces {...commonProps} />,
  teriyaki_sauce: <Sauces {...commonProps} />,
  bbq_sauce: <Sauces {...commonProps} />,
  tartar_sauce: <Sauces {...commonProps} />,
  soy_sauce: <Sauces {...commonProps} />,
  mustard: <Sauces {...commonProps} />,
  mayonnaise: <Sauces {...commonProps} />,
  ketchup: <Sauces {...commonProps} />,
  squid: <Squid {...commonProps} />,
  mussels: <Mussels {...commonProps} />,
  oysters: <Oysters {...commonProps} />,
  flounder: <Flounder {...commonProps} />,
  carp: <Fish {...commonProps} />,
  perch: <Fish {...commonProps} />,
  pike: <Fish {...commonProps} />,
  mackerel: <Fish {...commonProps} />,
  trout: <Fish {...commonProps} />,
  herring: <Fish {...commonProps} />,
  tuna: <Fish {...commonProps} />,
  cod: <Fish {...commonProps} />,
  salmon: <Fish {...commonProps} />,
  shrimp: <Shrimp {...commonProps} />,
  chicken: <Chicken {...commonProps} />,
  turkey: <Turkey {...commonProps} />,
  lamb: <Lamb {...commonProps} />,
  veal: <Veal {...commonProps} />,
  duck: <Duck {...commonProps} />,
  rabbit: <Rabbit {...commonProps} />,
  ground_meat: <GroundMeat {...commonProps} />,
  sausages: <Sausages {...commonProps} />,
  salami: <Salami {...commonProps} />,
  ham: <Ham {...commonProps} />,
  bacon: <Bacon {...commonProps} />,
  pork: <Pork {...commonProps} />,
  beef: <Beef {...commonProps} />,
  toilet_paper: <ToiletPaper {...commonProps} />,
  laundry_detergent: <LaundryDetergent {...commonProps} />,
  dish_sponges: <DishSponges {...commonProps} />,
  air_freshener: <AirFreshener {...commonProps} />,
  soap: <Soap {...commonProps} />,
  shampoo: <Shampoo {...commonProps} />,
  toothpaste: <Toothpaste {...commonProps} />,
  garbage_bags: <GarbageBags {...commonProps} />,
  light_bulbs: <LightBulbs {...commonProps} />,
  dish_soap: <DishSoap {...commonProps} />,
  wet_wipes: <WetWipes {...commonProps} />,
  paper_napkins: <PaperNapkins {...commonProps} />,
  rodent_food: <RodentFood {...commonProps} />,
  bird_food: <BirdFood {...commonProps} />,
  fish_food: <FishFood {...commonProps} />,
  cat_food: <CatFood {...commonProps} />,
  dog_food: <DogFood {...commonProps} />,
  sage: <Sage {...commonProps} />,
  garlic: <Garlic {...commonProps} />,
  apple: <AppleSvgComponent {...commonProps} />,
  carrot: <CarrotSvgComponent {...commonProps} />,
  apricot: <ApricotSvgComponent {...commonProps} />,
  avocado: <AvocadoSvgComponent {...commonProps} />,
  pineapple: <PineappleSvg {...commonProps} />,
  orange: <OrangeSvg {...commonProps} />,
  watermelon: <WatermelonSvg {...commonProps} />,
  artichoke: <ArtichokeSvg {...commonProps} />,
  basil: <BasilSvg {...commonProps} />,
  eggplant: <EggplantSvg {...commonProps} />,
  banana: <BananaSvg {...commonProps} />,
  sweet_potato: <SweetPotatoSvg {...commonProps} />,
  bell_pepper: <BellPepperSvg {...commonProps} />,
  broccoli: <BroccoliSvg {...commonProps} />,
  grapes: <GrapesSvg {...commonProps} />,
  peas: <PeasSvg {...commonProps} />,
  grapefruit: <GrapefruitSvg {...commonProps} />,
  melon: <MelonSvg {...commonProps} />,
  green_onion: <GreenOnionSVG {...commonProps} />,
  greens: <Greens {...commonProps} />,
  ginger: <Ginger {...commonProps} />,
  fig: <Fig {...commonProps} />,
  cabbage: <Cabbage {...commonProps} />,
  potato: <Potato {...commonProps} />,
  kiwi: <Kiwi {...commonProps} />,
  strawberry: <Strawberry {...commonProps} />,
  cranberry: <Cranberry {...commonProps} />,
  coriander: <Coriander {...commonProps} />,
  corn: <Corn {...commonProps} />,
  lime: <Lime {...commonProps} />,
  lemon: <Lemon {...commonProps} />,
  onion: <Onion {...commonProps} />,
  leek: <Leek {...commonProps} />,
  raspberry: <Raspberry {...commonProps} />,
  mango: <Mango {...commonProps} />,
  tangerines: <Tangerines {...commonProps} />,
  passion_fruit: <PassionFruit {...commonProps} />,
  mint: <Mint {...commonProps} />,
  nectarine: <Nectarine {...commonProps} />,
  cucumber: <Cucumber {...commonProps} />,
  olives: <Olives {...commonProps} />,
  chili_pepper: <ChiliPepper {...commonProps} />,
  peach: <Peach {...commonProps} />,
  parsley: <Parsley {...commonProps} />,
  tomatoes: <Tomatoes {...commonProps} />,
  cherry_tomatoes: <CherryTomatoes {...commonProps} />,
  radish: <Radish {...commonProps} />,
  arugula: <Arugula {...commonProps} />,
  lettuce: <Lettuce {...commonProps} />,
  beetroot: <Beetroot {...commonProps} />,
  celery: <Celery {...commonProps} />,
  plums: <Plums {...commonProps} />,
  asparagus: <Asparagus {...commonProps} />,
  pumpkin: <Pumpkin {...commonProps} />,
  dill: <Dill {...commonProps} />,
  dates: <Dates {...commonProps} />,
  cauliflower: <Cauliflower {...commonProps} />,
  zucchini: <Zucchini {...commonProps} />,
  cherry: <Cherry {...commonProps} />,
  blueberry: <Blueberry {...commonProps} />,
};

export const svgSchemeForAdding: SvgScheme = {
  wine: <Wine {...commonProps} />,
  absinthe: <Vermouth {...commonProps} />,
  sake: <Sake {...commonProps} />,
  vodka: <Alcohol {...commonProps} />,
  champagne: <Champagne {...commonProps} />,
  beer: <Beer {...commonProps} />,
  red_pepper: <Spices {...commonProps} />,
  toast_bread: <ToastBread {...commonProps} />,
  crispbread: <CrispBread {...commonProps} />,
  focaccia: <Focaccia {...commonProps} />,
  pita: <Pita {...commonProps} />,
  croissants: <Croissant {...commonProps} />,
  rye_bread: <Bread {...commonProps} />,
  buns: <Buns {...commonProps} />,
  french_baguette: <FrenchBaguette {...commonProps} />,
  eggs: <Eggs {...commonProps} />,
  butter: <Butter {...commonProps} />,
  cream: <Cream {...commonProps} />,
  kefir: <Milk {...commonProps} />,
  cottage_cheese: <CottageCheese {...commonProps} />,
  sour_cream: <SourCream {...commonProps} />,
  yogurt: <Yogurt {...commonProps} />,
  parmesan: <Cheese {...commonProps} />,
  feta: <Feta {...commonProps} />,
  tofu: <Tofu {...commonProps} />,
  mozzarella: <Mozzarella {...commonProps} />,
  salsa: <Sauces {...commonProps} />,
  squid: <Squid {...commonProps} />,
  mussels: <Mussels {...commonProps} />,
  oysters: <Oysters {...commonProps} />,
  flounder: <Flounder {...commonProps} />,
  carp: <Fish {...commonProps} />,
  shrimp: <Shrimp {...commonProps} />,
  chicken: <Chicken {...commonProps} />,
  turkey: <Turkey {...commonProps} />,
  lamb: <Lamb {...commonProps} />,
  veal: <Veal {...commonProps} />,
  duck: <Duck {...commonProps} />,
  rabbit: <Rabbit {...commonProps} />,
  ground_meat: <GroundMeat {...commonProps} />,
  sausages: <Sausages {...commonProps} />,
  salami: <Salami {...commonProps} />,
  ham: <Ham {...commonProps} />,
  bacon: <Bacon {...commonProps} />,
  pork: <Pork {...commonProps} />,
  beef: <Beef {...commonProps} />,
  toilet_paper: <ToiletPaper {...commonProps} />,
  laundry_detergent: <LaundryDetergent {...commonProps} />,
  dish_sponges: <DishSponges {...commonProps} />,
  air_freshener: <AirFreshener {...commonProps} />,
  soap: <Soap {...commonProps} />,
  shampoo: <Shampoo {...commonProps} />,
  toothpaste: <Toothpaste {...commonProps} />,
  garbage_bags: <GarbageBags {...commonProps} />,
  light_bulbs: <LightBulbs {...commonProps} />,
  dish_soap: <DishSoap {...commonProps} />,
  wet_wipes: <WetWipes {...commonProps} />,
  paper_napkins: <PaperNapkins {...commonProps} />,
  rodent_food: <RodentFood {...commonProps} />,
  bird_food: <BirdFood {...commonProps} />,
  fish_food: <FishFood {...commonProps} />,
  cat_food: <CatFood {...commonProps} />,
  dog_food: <DogFood {...commonProps} />,
  sage: <Sage {...commonProps} />,
  garlic: <Garlic {...commonProps} />,
  apple: <AppleSvgComponent {...commonProps} />,
  carrot: <CarrotSvgComponent {...commonProps} />,
  apricot: <ApricotSvgComponent {...commonProps} />,
  avocado: <AvocadoSvgComponent {...commonProps} />,
  pineapple: <PineappleSvg {...commonProps} />,
  orange: <OrangeSvg {...commonProps} />,
  watermelon: <WatermelonSvg {...commonProps} />,
  artichoke: <ArtichokeSvg {...commonProps} />,
  basil: <BasilSvg {...commonProps} />,
  eggplant: <EggplantSvg {...commonProps} />,
  banana: <BananaSvg {...commonProps} />,
  sweet_potato: <SweetPotatoSvg {...commonProps} />,
  bell_pepper: <BellPepperSvg {...commonProps} />,
  broccoli: <BroccoliSvg {...commonProps} />,
  grapes: <GrapesSvg {...commonProps} />,
  peas: <PeasSvg {...commonProps} />,
  grapefruit: <GrapefruitSvg {...commonProps} />,
  melon: <MelonSvg {...commonProps} />,
  green_onion: <GreenOnionSVG {...commonProps} />,
  greens: <Greens {...commonProps} />,
  ginger: <Ginger {...commonProps} />,
  fig: <Fig {...commonProps} />,
  cabbage: <Cabbage {...commonProps} />,
  potato: <Potato {...commonProps} />,
  kiwi: <Kiwi {...commonProps} />,
  strawberry: <Strawberry {...commonProps} />,
  cranberry: <Cranberry {...commonProps} />,
  coriander: <Coriander {...commonProps} />,
  corn: <Corn {...commonProps} />,
  lime: <Lime {...commonProps} />,
  lemon: <Lemon {...commonProps} />,
  onion: <Onion {...commonProps} />,
  leek: <Leek {...commonProps} />,
  raspberry: <Raspberry {...commonProps} />,
  mango: <Mango {...commonProps} />,
  tangerines: <Tangerines {...commonProps} />,
  passion_fruit: <PassionFruit {...commonProps} />,
  mint: <Mint {...commonProps} />,
  nectarine: <Nectarine {...commonProps} />,
  cucumber: <Cucumber {...commonProps} />,
  olives: <Olives {...commonProps} />,
  chili_pepper: <ChiliPepper {...commonProps} />,
  peach: <Peach {...commonProps} />,
  parsley: <Parsley {...commonProps} />,
  tomatoes: <Tomatoes {...commonProps} />,
  cherry_tomatoes: <CherryTomatoes {...commonProps} />,
  radish: <Radish {...commonProps} />,
  arugula: <Arugula {...commonProps} />,
  lettuce: <Lettuce {...commonProps} />,
  beetroot: <Beetroot {...commonProps} />,
  celery: <Celery {...commonProps} />,
  plums: <Plums {...commonProps} />,
  asparagus: <Asparagus {...commonProps} />,
  pumpkin: <Pumpkin {...commonProps} />,
  dill: <Dill {...commonProps} />,
  dates: <Dates {...commonProps} />,
  cauliflower: <Cauliflower {...commonProps} />,
  zucchini: <Zucchini {...commonProps} />,
  cherry: <Cherry {...commonProps} />,
  blueberry: <Blueberry {...commonProps} />,
};
